
services:
  app:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspaces/${localWorkspaceFolderBasename}:cached
      - node_modules:/workspaces/${localWorkspaceFolderBasename}/node_modules
    command: sleep infinity

volumes:
  node_modules:
