
services:
  app:
    # platform: linux/amd64
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/app:cached
    command: sleep infinity

volumes:
  node_modules:
