/**
 * @license
 * Copyright 2025 Porpoiseful LLC
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * @fileoverview Exposes translatable strings for use as Blockly.Msg tokens.
 * @author alan@porpoiseful.com (Alan Smith)
 */

import * as Blockly from 'blockly/core';

/**
 * Creates custom translation tokens for Blockly messages.
 * @param t Translation function that takes a key and returns translated string.
 * @return Object containing translated Blockly message tokens.
 */
export function customTokens(t: (key: string) => string): typeof Blockly.Msg {
  return {
    OF_TYPE: t('BLOCKLY.OF_TYPE'),
    WITH: t('BLOCKLY.WITH'),
    WHEN: t('BLOCKLY.WHEN'),
    PARAMETER: t('BLOCKLY.PARAMETER'),
    PARAMETERS: t('BLOCKLY.PARAMETERS'),
    PARAMETERS_CAN_ONLY_GO_IN_THEIR_METHODS_BLOCK:
      t('BLOCKLY.PARAMETERS_CAN_ONLY_GO_IN_THEIR_METHODS_BLOCK'),
    PARAMETER_DOES_NOT_EXIST_IN_METHOD:
      t('BLOCKLY.PARAMETER_DOES_NOT_EXIST_IN_METHOD'),
    PARAMETER_DOES_NOT_EXIST_IN_EVENT_HANDLER:
      t('BLOCKLY.PARAMETER_DOES_NOT_EXIST_IN_EVENT_HANDLER'),
    NO_PARAMETER_SELECTED:
      t('BLOCKLY.NO_PARAMETER_SELECTED'),
    CLASS_METHOD_DEF_ALREADY_ON_WORKSPACE:
      t('BLOCKLY.CLASS_METHOD_DEF_ALREADY_ON_WORKSPACE'),
    EVENT_HANDLER_ALREADY_ON_WORKSPACE:
      t('BLOCKLY.EVENT_HANDLER_ALREADY_ON_WORKSPACE'),
    EVENT_HANDLER_ROBOT_EVENT_NOT_FOUND:
      t('BLOCKLY.EVENT_HANDLER_ROBOT_EVENT_NOT_FOUND'),
    EVENT_HANDLER_MECHANISM_EVENT_NOT_FOUND:
      t('BLOCKLY.EVENT_HANDLER_MECHANISM_EVENT_NOT_FOUND'),
    EVENT_HANDLER_MECHANISM_NOT_FOUND:
      t('BLOCKLY.EVENT_HANDLER_MECHANISM_NOT_FOUND'),
    MECHANISMS: t('MECHANISMS'),
    OPMODES: t('OPMODES'),
    COMPONENTS: t('BLOCKLY.COMPONENTS'),
    COMPONENTS_TOOLTIP: t('BLOCKLY.TOOLTIP.COMPONENTS'),
    PRIVATE_COMPONENTS: t('BLOCKLY.PRIVATE_COMPONENTS'),
    PRIVATE_COMPONENTS_TOOLTIP: t('BLOCKLY.TOOLTIP.PRIVATE_COMPONENTS'),
    EVENTS: t('BLOCKLY.EVENTS'),
    EVALUATE_BUT_IGNORE_RESULT: t('BLOCKLY.EVALUATE_BUT_IGNORE_RESULT'),
    EVALUATE_BUT_IGNORE_RESULT_TOOLTIP:
      t('BLOCKLY.TOOLTIP.EVALUATE_BUT_IGNORE_RESULT'),
    NONE: t('BLOCKLY.NONE'),
    NONE_TOOLTIP: t('BLOCKLY.TOOLTIP.NONE'),
    AUTO: t('BLOCKLY.AUTO'),
    TELEOP: t('BLOCKLY.TELEOP'),
    TEST: t('BLOCKLY.TEST'),
    TYPE: t('BLOCKLY.TYPE'),
    ENABLED: t('BLOCKLY.ENABLED'),
    DISPLAY_NAME: t('BLOCKLY.DISPLAY_NAME'),
    DISPLAY_GROUP: t('BLOCKLY.DISPLAY_GROUP'),
    NO_MECHANISM_CONTENTS: t('BLOCKLY.NO_MECHANISM_CONTENTS'),
    OPMODE_TYPE_TOOLTIP: t('BLOCKLY.TOOLTIP.OPMODE_TYPE'),
    OPMODE_ENABLED_TOOLTIP: t('BLOCKLY.TOOLTIP.OPMODE_ENABLED'),
    OPMODE_NAME_TOOLTIP: t('BLOCKLY.TOOLTIP.OPMODE_NAME'),
    OPMODE_GROUP_TOOLTIP: t('BLOCKLY.TOOLTIP.OPMODE_GROUP'),
    CALL: t('BLOCKLY.CALL'),
    ROBOT_LOWER_CASE: t('BLOCKLY.ROBOT_LOWER_CASE'),
    CREATE: t('BLOCKLY.CREATE'),
    FIRE: t('BLOCKLY.FIRE'),
    GET: t('BLOCKLY.GET'),
    GET_MODULE_VARIABLE_TOOLTIP: t('BLOCKLY.TOOLTIP.GET_MODULE_VARIABLE'),
    GET_CLASS_VARIABLE_TOOLTIP: t('BLOCKLY.TOOLTIP.GET_CLASS_VARIABLE'),
    GET_INSTANCE_VARIABLE_TOOLTIP: t('BLOCKLY.TOOLTIP.GET_INSTANCE_VARIABLE'),
    GET_ENUM_VALUE_TOOLTIP: t('BLOCKLY.TOOLTIP.GET_ENUM_VALUE'),
    SET: t('BLOCKLY.SET'),
    TO: t('BLOCKLY.TO'),
    CAPTION: t('BLOCKLY.CAPTION'),
    VALUE: t('BLOCKLY.VALUE'),
    DISPLAY_ADD_DATA_TOOLTIP: t('BLOCKLY.TOOLTIP.DISPLAY_ADD_DATA'),
    GAMEPAD: t('BLOCKLY.GAMEPAD.TITLE'),
    GAMEPAD_BUTTON_A: t('BLOCKLY.GAMEPAD.BUTTON_A'),
    GAMEPAD_BUTTON_B: t('BLOCKLY.GAMEPAD.BUTTON_B'),
    GAMEPAD_BUTTON_X: t('BLOCKLY.GAMEPAD.BUTTON_X'),
    GAMEPAD_BUTTON_Y: t('BLOCKLY.GAMEPAD.BUTTON_Y'),
    GAMEPAD_BUTTON_SOUTH_FACE: t('BLOCKLY.GAMEPAD.BUTTON_SOUTH_FACE'),
    GAMEPAD_BUTTON_EAST_FACE: t('BLOCKLY.GAMEPAD.BUTTON_EAST_FACE'),
    GAMEPAD_BUTTON_WEST_FACE: t('BLOCKLY.GAMEPAD.BUTTON_WEST_FACE'),
    GAMEPAD_BUTTON_NORTH_FACE: t('BLOCKLY.GAMEPAD.BUTTON_NORTH_FACE'),
    GAMEPAD_BUTTON_CROSS: t('BLOCKLY.GAMEPAD.BUTTON_CROSS'),
    GAMEPAD_BUTTON_CIRCLE: t('BLOCKLY.GAMEPAD.BUTTON_CIRCLE'),
    GAMEPAD_BUTTON_SQUARE: t('BLOCKLY.GAMEPAD.BUTTON_SQUARE'),
    GAMEPAD_BUTTON_TRIANGLE: t('BLOCKLY.GAMEPAD.BUTTON_TRIANGLE'),
    GAMEPAD_DPAD_UP: t('BLOCKLY.GAMEPAD.DPAD_UP'),
    GAMEPAD_DPAD_DOWN: t('BLOCKLY.GAMEPAD.DPAD_DOWN'),
    GAMEPAD_DPAD_LEFT: t('BLOCKLY.GAMEPAD.DPAD_LEFT'),
    GAMEPAD_DPAD_RIGHT: t('BLOCKLY.GAMEPAD.DPAD_RIGHT'),
    GAMEPAD_BUTTON_DPAD_UP: t('BLOCKLY.GAMEPAD.DPAD_UP'),
    GAMEPAD_BUTTON_DPAD_DOWN: t('BLOCKLY.GAMEPAD.DPAD_DOWN'),
    GAMEPAD_BUTTON_DPAD_LEFT: t('BLOCKLY.GAMEPAD.DPAD_LEFT'),
    GAMEPAD_BUTTON_DPAD_RIGHT: t('BLOCKLY.GAMEPAD.DPAD_RIGHT'),
    GAMEPAD_LEFT_BUMPER: t('BLOCKLY.GAMEPAD.LEFT_BUMPER'),
    GAMEPAD_RIGHT_BUMPER: t('BLOCKLY.GAMEPAD.RIGHT_BUMPER'),
    GAMEPAD_BUTTON_LEFT_BUMPER: t('BLOCKLY.GAMEPAD.LEFT_BUMPER'),
    GAMEPAD_BUTTON_RIGHT_BUMPER: t('BLOCKLY.GAMEPAD.RIGHT_BUMPER'),
    GAMEPAD_BACK: t('BLOCKLY.GAMEPAD.BACK'),
    GAMEPAD_START: t('BLOCKLY.GAMEPAD.START'),
    GAMEPAD_GUIDE: t('BLOCKLY.GAMEPAD.GUIDE'),
    GAMEPAD_BUTTON_BACK: t('BLOCKLY.GAMEPAD.BACK'),
    GAMEPAD_BUTTON_START: t('BLOCKLY.GAMEPAD.START'),
    GAMEPAD_BUTTON_GUIDE: t('BLOCKLY.GAMEPAD.GUIDE'),
    GAMEPAD_LEFT_STICK_BUTTON: t('BLOCKLY.GAMEPAD.LEFT_STICK_BUTTON'),
    GAMEPAD_RIGHT_STICK_BUTTON: t('BLOCKLY.GAMEPAD.RIGHT_STICK_BUTTON'),
    GAMEPAD_BUTTON_LEFT_STICK: t('BLOCKLY.GAMEPAD.LEFT_STICK_BUTTON'),
    GAMEPAD_BUTTON_RIGHT_STICK: t('BLOCKLY.GAMEPAD.RIGHT_STICK_BUTTON'),
    GAMEPAD_BUTTON_TOUCHPAD: t('BLOCKLY.GAMEPAD.BUTTON_TOUCHPAD'),
    GAMEPAD_BUTTON_MISC1: t('BLOCKLY.GAMEPAD.BUTTON_MISC1'),
    GAMEPAD_BUTTON_MISC2: t('BLOCKLY.GAMEPAD.BUTTON_MISC2'),
    GAMEPAD_BUTTON_MISC3: t('BLOCKLY.GAMEPAD.BUTTON_MISC3'),
    GAMEPAD_BUTTON_MISC4: t('BLOCKLY.GAMEPAD.BUTTON_MISC4'),
    GAMEPAD_BUTTON_MISC5: t('BLOCKLY.GAMEPAD.BUTTON_MISC5'),
    GAMEPAD_BUTTON_MISC6: t('BLOCKLY.GAMEPAD.BUTTON_MISC6'),
    GAMEPAD_BUTTON_LEFT_PADDLE_1: t('BLOCKLY.GAMEPAD.BUTTON_LEFT_PADDLE_1'),
    GAMEPAD_BUTTON_RIGHT_PADDLE_1: t('BLOCKLY.GAMEPAD.BUTTON_RIGHT_PADDLE_1'),
    GAMEPAD_BUTTON_LEFT_PADDLE_2: t('BLOCKLY.GAMEPAD.BUTTON_LEFT_PADDLE_2'),
    GAMEPAD_BUTTON_RIGHT_PADDLE_2: t('BLOCKLY.GAMEPAD.BUTTON_RIGHT_PADDLE_2'),
    GAMEPAD_LEFT_STICK_X: t('BLOCKLY.GAMEPAD.LEFT_STICK_X'),
    GAMEPAD_LEFT_STICK_Y: t('BLOCKLY.GAMEPAD.LEFT_STICK_Y'),
    GAMEPAD_RIGHT_STICK_X: t('BLOCKLY.GAMEPAD.RIGHT_STICK_X'),
    GAMEPAD_RIGHT_STICK_Y: t('BLOCKLY.GAMEPAD.RIGHT_STICK_Y'),
    GAMEPAD_LEFT_TRIGGER: t('BLOCKLY.GAMEPAD.LEFT_TRIGGER'),
    GAMEPAD_RIGHT_TRIGGER: t('BLOCKLY.GAMEPAD.RIGHT_TRIGGER'),
    GAMEPAD_AXIS_LEFT_STICK_X: t('BLOCKLY.GAMEPAD.LEFT_STICK_X'),
    GAMEPAD_AXIS_LEFT_STICK_Y: t('BLOCKLY.GAMEPAD.LEFT_STICK_Y'),
    GAMEPAD_AXIS_RIGHT_STICK_X: t('BLOCKLY.GAMEPAD.RIGHT_STICK_X'),
    GAMEPAD_AXIS_RIGHT_STICK_Y: t('BLOCKLY.GAMEPAD.RIGHT_STICK_Y'),
    GAMEPAD_AXIS_LEFT_TRIGGER: t('BLOCKLY.GAMEPAD.LEFT_TRIGGER'),
    GAMEPAD_AXIS_RIGHT_TRIGGER: t('BLOCKLY.GAMEPAD.RIGHT_TRIGGER'),
    GAMEPAD_RUMBLE_LEFT: t('BLOCKLY.GAMEPAD.RUMBLE_LEFT'),
    GAMEPAD_RUMBLE_RIGHT: t('BLOCKLY.GAMEPAD.RUMBLE_RIGHT'),
    GAMEPAD_RUMBLE_LEFT_TRIGGER: t('BLOCKLY.GAMEPAD.RUMBLE_LEFT_TRIGGER'),
    GAMEPAD_RUMBLE_RIGHT_TRIGGER: t('BLOCKLY.GAMEPAD.RUMBLE_RIGHT_TRIGGER'),
    GAMEPAD_LEDS: t('BLOCKLY.GAMEPAD.LEDS'),
    GAMEPAD_IS_DOWN: t('BLOCKLY.GAMEPAD.IS_DOWN'),
    GAMEPAD_PRESSED: t('BLOCKLY.GAMEPAD.PRESSED'),
    GAMEPAD_RELEASED: t('BLOCKLY.GAMEPAD.RELEASED'),
    GAMEPAD_EVENT_PRESSED: t('BLOCKLY.GAMEPAD.EVENT_PRESSED'),
    GAMEPAD_EVENT_RELEASED: t('BLOCKLY.GAMEPAD.EVENT_RELEASED'),
    GAMEPAD_EVENT_CHANGED: t('BLOCKLY.GAMEPAD.EVENT_CHANGED'),
    SET_MODULE_VARIABLE_TOOLTIP: t('BLOCKLY.TOOLTIP.SET_MODULE_VARIABLE'),
    SET_CLASS_VARIABLE_TOOLTIP: t('BLOCKLY.TOOLTIP.SET_CLASS_VARIABLE'),
    SET_INSTANCE_VARIABLE_TOOLTIP: t('BLOCKLY.TOOLTIP.SET_INSTANCE_VARIABLE'),
    VAR_KIND_MUST_BE_MODULE_CLASS_OR_INSTANCE: t('BLOCKLY.ERROR.VAR_KIND_MUST_BE_MODULE_CLASS_OR_INSTANCE'),
    MECHANISM_NOT_FOUND_WARNING: t('BLOCKLY.WARNING.MECHANISM_NOT_FOUND'),
    WARNING_GET_ENUM_VALUE_MISSING_ENUM: t('BLOCKLY.WARNING.GET_ENUM_VALUE_MISSING_ENUM'),
    WARNING_GET_ENUM_VALUE_MISSING_VALUE: t('BLOCKLY.WARNING.GET_ENUM_VALUE_MISSING_VALUE'),
    WARNING_GET_MODULE_VARIABLE_MISSING_MODULE: t('BLOCKLY.WARNING.GET_MODULE_VARIABLE_MISSING_MODULE'),
    WARNING_GET_MODULE_VARIABLE_MISSING_VARIABLE: t('BLOCKLY.WARNING.GET_MODULE_VARIABLE_MISSING_VARIABLE'),
    WARNING_GET_CLASS_VARIABLE_MISSING_CLASS: t('BLOCKLY.WARNING.GET_CLASS_VARIABLE_MISSING_CLASS'),
    WARNING_GET_CLASS_VARIABLE_MISSING_VARIABLE: t('BLOCKLY.WARNING.GET_CLASS_VARIABLE_MISSING_VARIABLE'),
    WARNING_GET_INSTANCE_VARIABLE_MISSING_CLASS: t('BLOCKLY.WARNING.GET_INSTANCE_VARIABLE_MISSING_CLASS'),
    WARNING_GET_INSTANCE_VARIABLE_MISSING_VARIABLE: t('BLOCKLY.WARNING.GET_INSTANCE_VARIABLE_MISSING_VARIABLE'),
    WARNING_SET_MODULE_VARIABLE_MISSING_MODULE: t('BLOCKLY.WARNING.SET_MODULE_VARIABLE_MISSING_MODULE'),
    WARNING_SET_MODULE_VARIABLE_MISSING_VARIABLE: t('BLOCKLY.WARNING.SET_MODULE_VARIABLE_MISSING_VARIABLE'),
    WARNING_SET_MODULE_VARIABLE_NOT_SETTABLE: t('BLOCKLY.WARNING.SET_MODULE_VARIABLE_NOT_SETTABLE'),
    WARNING_SET_CLASS_VARIABLE_MISSING_CLASS: t('BLOCKLY.WARNING.SET_CLASS_VARIABLE_MISSING_CLASS'),
    WARNING_SET_CLASS_VARIABLE_MISSING_VARIABLE: t('BLOCKLY.WARNING.SET_CLASS_VARIABLE_MISSING_VARIABLE'),
    WARNING_SET_CLASS_VARIABLE_NOT_SETTABLE: t('BLOCKLY.WARNING.SET_CLASS_VARIABLE_NOT_SETTABLE'),
    WARNING_SET_INSTANCE_VARIABLE_MISSING_CLASS: t('BLOCKLY.WARNING.SET_INSTANCE_VARIABLE_MISSING_CLASS'),
    WARNING_SET_INSTANCE_VARIABLE_MISSING_VARIABLE: t('BLOCKLY.WARNING.SET_INSTANCE_VARIABLE_MISSING_VARIABLE'),
    WARNING_SET_INSTANCE_VARIABLE_NOT_SETTABLE: t('BLOCKLY.WARNING.SET_INSTANCE_VARIABLE_NOT_SETTABLE'),
    WARNING_CALL_MODULE_FUNCTION_MISSING_MODULE: t('BLOCKLY.WARNING.CALL_MODULE_FUNCTION_MISSING_MODULE'),
    WARNING_CALL_MODULE_FUNCTION_MISSING_FUNCTION: t('BLOCKLY.WARNING.CALL_MODULE_FUNCTION_MISSING_FUNCTION'),
    WARNING_CALL_STATIC_METHOD_MISSING_CLASS: t('BLOCKLY.WARNING.CALL_STATIC_METHOD_MISSING_CLASS'),
    WARNING_CALL_STATIC_METHOD_MISSING_METHOD: t('BLOCKLY.WARNING.CALL_STATIC_METHOD_MISSING_METHOD'),
    WARNING_CALL_CONSTRUCTOR_MISSING_CLASS: t('BLOCKLY.WARNING.CALL_CONSTRUCTOR_MISSING_CLASS'),
    WARNING_CALL_CONSTRUCTOR_MISSING_CONSTRUCTOR: t('BLOCKLY.WARNING.CALL_CONSTRUCTOR_MISSING_CONSTRUCTOR'),
    WARNING_CALL_INSTANCE_METHOD_MISSING_CLASS: t('BLOCKLY.WARNING.CALL_INSTANCE_METHOD_MISSING_CLASS'),
    WARNING_CALL_INSTANCE_METHOD_MISSING_METHOD: t('BLOCKLY.WARNING.CALL_INSTANCE_METHOD_MISSING_METHOD'),
    WARNING_CALL_INSTANCE_WITHIN_METHOD_MISSING_METHOD: t('BLOCKLY.WARNING.CALL_INSTANCE_WITHIN_METHOD_MISSING_METHOD'),
    WARNING_CALL_COMPONENT_INSTANCE_METHOD_PRIVATE_COMPONENT: t('BLOCKLY.WARNING.CALL_COMPONENT_INSTANCE_METHOD_PRIVATE_COMPONENT'),
    WARNING_CALL_COMPONENT_INSTANCE_METHOD_MISSING_COMPONENT: t('BLOCKLY.WARNING.CALL_COMPONENT_INSTANCE_METHOD_MISSING_COMPONENT'),
    WARNING_CALL_COMPONENT_INSTANCE_METHOD_MISSING_COMPONENT_CLASS: t('BLOCKLY.WARNING.CALL_COMPONENT_INSTANCE_METHOD_MISSING_COMPONENT_CLASS'),
    WARNING_CALL_COMPONENT_INSTANCE_METHOD_MISSING_METHOD: t('BLOCKLY.WARNING.CALL_COMPONENT_INSTANCE_METHOD_MISSING_METHOD'),
    WARNING_CALL_MECHANISM_COMPONENT_INSTANCE_METHOD_MISSING_MECHANISM: t('BLOCKLY.WARNING.CALL_MECHANISM_COMPONENT_INSTANCE_METHOD_MISSING_MECHANISM'),
    WARNING_CALL_ROBOT_INSTANCE_METHOD_INSIDE_MECHANISM: t('BLOCKLY.WARNING.CALL_ROBOT_INSTANCE_METHOD_INSIDE_MECHANISM'),
    WARNING_CALL_ROBOT_INSTANCE_METHOD_MISSING_METHOD: t('BLOCKLY.WARNING.CALL_ROBOT_INSTANCE_METHOD_MISSING_METHOD'),
    WARNING_CALL_MECHANISM_INSTANCE_METHOD_INSIDE_MECHANISM: t('BLOCKLY.WARNING.CALL_MECHANISM_INSTANCE_METHOD_INSIDE_MECHANISM'),
    WARNING_CALL_MECHANISM_INSTANCE_METHOD_MISSING_METHOD: t('BLOCKLY.WARNING.CALL_MECHANISM_INSTANCE_METHOD_MISSING_METHOD'),
    WARNING_CALL_MECHANISM_INSTANCE_METHOD_MISSING_MECHANISM: t('BLOCKLY.WARNING.CALL_MECHANISM_INSTANCE_METHOD_MISSING_MECHANISM'),
    CALL_BUILTIN_FUNCTION_TOOLTIP: t('BLOCKLY.TOOLTIP.CALL_BUILTIN_FUNCTION'),
    CALL_MODULE_FUNCTION_TOOLTIP: t('BLOCKLY.TOOLTIP.CALL_MODULE_FUNCTION'),
    CALL_STATIC_METHOD_TOOLTIP: t('BLOCKLY.TOOLTIP.CALL_STATIC_METHOD'),
    CALL_CONSTRUCTOR_TOOLTIP: t('BLOCKLY.TOOLTIP.CALL_CONSTRUCTOR'),
    CALL_INSTANCE_METHOD_TOOLTIP: t('BLOCKLY.TOOLTIP.CALL_INSTANCE_METHOD'),
    CALL_INSTANCE_METHOD_WITHIN_TOOLTIP: t('BLOCKLY.TOOLTIP.CALL_INSTANCE_METHOD_WITHIN'),
    FIRE_EVENT_TOOLTIP: t('BLOCKLY.TOOLTIP.FIRE_EVENT'),
    CALL_MECHANISM_COMPONENT_INSTANCE_METHOD_TOOLTIP: t('BLOCKLY.TOOLTIP.CALL_MECHANISM_COMPONENT_INSTANCE_METHOD'),
    CALL_COMPONENT_INSTANCE_METHOD_TOOLTIP: t('BLOCKLY.TOOLTIP.CALL_COMPONENT_INSTANCE_METHOD'),
    CALL_ROBOT_INSTANCE_METHOD_TOOLTIP: t('BLOCKLY.TOOLTIP.CALL_ROBOT_INSTANCE_METHOD'),
    CALL_MECHANISM_INSTANCE_METHOD_TOOLTIP: t('BLOCKLY.TOOLTIP.CALL_MECHANISM_INSTANCE_METHOD'),
    WARNING_EVENT_NOT_IN_HOLDER: t('BLOCKLY.WARNING.EVENT_NOT_IN_HOLDER'),
    WARNING_COMPONENT_NOT_IN_HOLDER: t('BLOCKLY.WARNING.COMPONENT_NOT_IN_HOLDER'),
    WARNING_MECHANISM_NOT_IN_HOLDER: t('BLOCKLY.WARNING.MECHANISM_NOT_IN_HOLDER'),
    WARNING_COMPONENT_MISSING_COMPONENT_CLASS: t('BLOCKLY.WARNING.COMPONENT_MISSING_COMPONENT_CLASS'),
    WARNING_OPMODE_STEPS_OR_PERIODIC_REQUIRED: t('BLOCKLY.WARNING.OPMODE_STEPS_OR_PERIODIC_REQUIRED'),
    MRC_CATEGORY_HARDWARE: t('BLOCKLY.CATEGORY.HARDWARE'),
    MRC_CATEGORY_ROBOT: t('BLOCKLY.CATEGORY.ROBOT'),
    MRC_CATEGORY_COMPONENTS: t('BLOCKLY.CATEGORY.COMPONENTS'),
    MRC_CATEGORY_MECHANISMS: t('BLOCKLY.CATEGORY.MECHANISMS'),
    MRC_CATEGORY_LOGIC: t('BLOCKLY.CATEGORY.LOGIC'),
    MRC_CATEGORY_LOOPS: t('BLOCKLY.CATEGORY.LOOPS'),
    MRC_CATEGORY_LISTS: t('BLOCKLY.CATEGORY.LISTS'),
    MRC_CATEGORY_MATH: t('BLOCKLY.CATEGORY.MATH'),
    MRC_CATEGORY_TEXT: t('BLOCKLY.CATEGORY.TEXT'),
    MRC_CATEGORY_MISC: t('BLOCKLY.CATEGORY.MISC'),
    MRC_CATEGORY_VARIABLES: t('BLOCKLY.CATEGORY.VARIABLES'),
    MRC_CATEGORY_METHODS: t('BLOCKLY.CATEGORY.METHODS'),
    MRC_CATEGORY_EVENTS: t('BLOCKLY.CATEGORY.EVENTS'),
    MRC_CATEGORY_ADD_MECHANISM: t('BLOCKLY.CATEGORY.ADD_MECHANISM'),
    MRC_CATEGORY_ADD_COMPONENT: t('BLOCKLY.CATEGORY.ADD_COMPONENT'),
    MRC_CATEGORY_TEST: t('BLOCKLY.CATEGORY.TEST'),
    MRC_CATEGORY_DRIVER_STATION: t('BLOCKLY.CATEGORY.DRIVER_STATION'),
    MRC_CATEGORY_DRIVER_STATION_DISPLAY: t('BLOCKLY.CATEGORY.DRIVER_STATION_DISPLAY'),
    MRC_CATEGORY_DRIVER_STATION_GAMEPADS: t('BLOCKLY.CATEGORY.DRIVER_STATION_GAMEPADS'),
    MRC_CONFIG_GAMEPADS_BUTTON: t('BLOCKLY.CONFIG_GAMEPADS_BUTTON'),
    MRC_PRINT: t('BLOCKLY.PRINT'),
    CUSTOM_EVENTS_LABEL: t('BLOCKLY.CUSTOM_EVENTS_LABEL'),
    CUSTOM_METHODS_LABEL: t('BLOCKLY.CUSTOM_METHODS_LABEL'),
    MORE_ROBOT_METHODS_LABEL: t('BLOCKLY.MORE_ROBOT_METHODS_LABEL'),
    MORE_MECHANISM_METHODS_LABEL: t('BLOCKLY.MORE_MECHANISM_METHODS_LABEL'),
    MORE_OPMODE_METHODS_LABEL: t('BLOCKLY.MORE_OPMODE_METHODS_LABEL'),
    COMMENT_DEFAULT_TEXT: t('BLOCKLY.COMMENT_DEFAULT_TEXT'),
    STEPS: t('BLOCKLY.STEPS'),
    REPEAT_UNTIL: t('BLOCKLY.REPEAT_UNTIL'),
    JUMP_TO:  t('BLOCKLY.JUMP_TO'),
    JUMP_TO_STEP_TOOLTIP: t('BLOCKLY.TOOLTIP.JUMP_TO_STEP'),
    JUMP_CAN_ONLY_GO_IN_THEIR_STEPS_BLOCK: t('BLOCKLY.JUMP_CAN_ONLY_GO_IN_THEIR_STEPS_BLOCK'),
    STEP_DOES_NOT_EXIST_IN_STEPS: t('BLOCKLY.STEP_DOES_NOT_EXIST_IN_STEPS'),
    NO_STEP_SELECTED: t('BLOCKLY.NO_STEP_SELECTED'),
    NO_STEPS: t('BLOCKLY.NO_STEPS'),
  }
};

/**
 * Replaces tokens in a string with values from a dictionary.
 * @param template String containing tokens in the format {{token}}
 * @param values Dictionary mapping token names to their replacement values
 * @return String with all tokens replaced by their corresponding values
 */
export function replaceTokens(template: string, values: Record<string, string>): string {
  return template.replace(/\{\{(\w+)\}\}/g, (match, token) => {
    return values[token] !== undefined ? values[token] : match;
  });
}
